export const progress = {};
progress.INIT_PROGRESS = 1;
progress.LOGGING_IN = 2;
progress.LOGGED_IN = 4;
progress.SCRAPING = 8;
progress.SCRAPED = 16;
progress.LOGGING_OUT = 32;
progress.LOGGED_OUT = 64;
progress.HIDE_PROGRESS = 128;
